src/Entity/FactureDon.php
<?php

namespace App\Entity;

use App\Repository\FactureDonRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: FactureDonRepository::class)]
class FactureDon
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Nom du donateur ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "Le champ Nom du donateur ne peut pas dépasser 255 caractères.")]
    #[Assert\Regex(
        pattern: '/^\D+$/',
        message: "Le champ Nom du donateur ne peut pas contenir des chiffres."
    )]
    private ?string $nom_donateur = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Prénom du donateur ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "Le champ Prénom du donateur ne peut pas dépasser 255 caractères.")]
    #[Assert\Regex(
        pattern: '/^\D+$/',
        message: "Le champ Prénom du donateur ne peut pas contenir des chiffres."
    )]
    private ?string $prenom_donateur = null;
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Email ne peut pas être vide.")]
    #[Assert\Email(message: "L'email '{{ value }}' n'est pas valide.")]
    private ?string $email = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Adresse ne peut pas être vide.")]
    #[Assert\Length(max: 255, maxMessage: "Le champ Adresse ne peut pas dépasser 255 caractères.")]
    private ?string $adresses = null;

    #[ORM\Column(type: 'integer')]
    #[Assert\NotBlank(message: "Le champ Numéro de téléphone ne peut pas être vide.")]
    #[Assert\Type(type: 'integer', message: "Le numéro de téléphone doit être un entier.")]
    private ?int $numero_telephone = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ Description ne peut pas être vide.")]
    #[Assert\Length(
        min: 4,
        minMessage: "Le champ Description doit avoir au moins 4 caractères.",
        max: 255,
        maxMessage: "Le champ Description ne peut pas dépasser 255 caractères."
    )]

    
    private ?string $description = null;

  

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomDonateur(): ?string
    {
        return $this->nom_donateur;
    }

    public function setNomDonateur(string $nom_donateur): static
    {
        $this->nom_donateur = $nom_donateur;

        return $this;
    }

    public function getPrenomDonateur(): ?string
    {
        return $this->prenom_donateur;
    }

    public function setPrenomDonateur(string $prenom_donateur): static
    {
        $this->prenom_donateur = $prenom_donateur;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getAdresses(): ?string
    {
        return $this->adresses;
    }

    public function setAdresses(string $adresses): static
    {
        $this->adresses = $adresses;

        return $this;
    }

    public function getNumeroTelephone(): ?int
    {
        return $this->numero_telephone;
    }

    public function setNumeroTelephone(int $numero_telephone): static
    {
        $this->numero_telephone = $numero_telephone;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    private ?Don $Don = null;

    public function getDon(): ?Don
    {
        return $this->Don;
    }

    public function setDon(?Don $Don): static
    {
        $this->Don = $Don;

        return $this;
    }

    
}

src/Controller/FacturedonbackController.php
<?php

namespace App\Controller;

use App\Entity\FactureDon;
use App\Form\FactureDon1Type;
use App\Repository\FactureDonRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/facturedonback')]
class FacturedonbackController extends AbstractController
{
    #[Route('/', name: 'app_facturedonback_index', methods: ['GET'])]
    public function index(FactureDonRepository $factureDonRepository): Response
    {
        return $this->render('facturedonback/index.html.twig', [
            'facture_dons' => $factureDonRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_facturedonback_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $factureDon = new FactureDon();
        $form = $this->createForm(FactureDon1Type::class, $factureDon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($factureDon);
            $entityManager->flush();

            return $this->redirectToRoute('app_facturedonback_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('facturedonback/new.html.twig', [
            'facture_don' => $factureDon,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_facturedonback_show', methods: ['GET'])]
    public function show(FactureDon $factureDon): Response
    {
        return $this->render('facturedonback/show.html.twig', [
            'facture_don' => $factureDon,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_facturedonback_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, FactureDon $factureDon, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(FactureDon1Type::class, $factureDon);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_facturedonback_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('facturedonback/edit.html.twig', [
            'facture_don' => $factureDon,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_facturedonback_delete', methods: ['POST'])]
    public function delete(Request $request, FactureDon $factureDon, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$factureDon->getId(), $request->request->get('_token'))) {
            $entityManager->remove($factureDon);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_facturedonback_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/facturedonback/_delete_form.html.twig
<form method="post" action="{{ path('app_facturedonback_delete', {'id': facture_don.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ facture_don.id) }}">
    <button class="btn">Delete</button>
</form>

templates/facturedonback/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit FactureDon{% endblock %}

{% block body %}
    <h1>Edit FactureDon</h1>

    {{ include('facturedonback/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_facturedonback_index') }}">back to list</a>

    {{ include('facturedonback/_delete_form.html.twig') }}
{% endblock %}

templates/facturedonback/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}FactureDon index{% endblock %}

{% block body %}
    <h1>FactureDon index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_donateur</th>
                <th>Prenom_donateur</th>
                <th>Email</th>
                <th>Adresses</th>
                <th>Numero_telephone</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for facture_don in facture_dons %}
            <tr>
                <td>{{ facture_don.id }}</td>
                <td>{{ facture_don.nomDonateur }}</td>
                <td>{{ facture_don.prenomDonateur }}</td>
                <td>{{ facture_don.email }}</td>
                <td>{{ facture_don.adresses }}</td>
                <td>{{ facture_don.numeroTelephone }}</td>
                <td>{{ facture_don.description }}</td>
                <td>
                    <a href="{{ path('app_facturedonback_show', {'id': facture_don.id}) }}">show</a>
                    <a href="{{ path('app_facturedonback_edit', {'id': facture_don.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_facturedonback_new') }}">Create new</a>
{% endblock %}

templates/facturedonback/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New FactureDon{% endblock %}

{% block body %}
    <h1>Create new FactureDon</h1>

    {{ include('facturedonback/_form.html.twig') }}

    <a href="{{ path('app_don_new') }}">back to list</a>
{% endblock %}

templates/facturedonback/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}FactureDon{% endblock %}

{% block body %}
    <h1>FactureDon</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ facture_don.id }}</td>
            </tr>
            <tr>
                <th>Nom_donateur</th>
                <td>{{ facture_don.nomDonateur }}</td>
            </tr>
            <tr>
                <th>Prenom_donateur</th>
                <td>{{ facture_don.prenomDonateur }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ facture_don.email }}</td>
            </tr>
            <tr>
                <th>Adresses</th>
                <td>{{ facture_don.adresses }}</td>
            </tr>
            <tr>
                <th>Numero_telephone</th>
                <td>{{ facture_don.numeroTelephone }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ facture_don.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_facturedonback_index') }}">back to list</a>

    <a href="{{ path('app_facturedonback_edit', {'id': facture_don.id}) }}">edit</a>

    {{ include('facturedonback/_delete_form.html.twig') }}
{% endblock %}